AWSTemplateFormatVersion: '2010-09-09'
Description: Amplify App for House Expenses App
Resources:
  HouseExpensesAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: HouseExpensesAmplifyApp
      Repository: <GITHUB_REPO_URL>
      Platform: WEB
      BuildSpec: |
        version: 1.0
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
